# Generated by Django 5.2.9 on 2025-12-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('TRAVEL', 'Travel'), ('EXPENSE', 'Expense')], default='TRAVEL', max_length=20)),
                ('description', models.TextField()),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum threshold for rule to apply', max_digits=10, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum threshold (if any)', max_digits=10, null=True)),
                ('require_finance_approval', models.BooleanField(default=False)),
                ('auto_flag', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
